# Generated by Django 5.2.8 on 2025-11-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='List ingredients separated by newlines')),
                ('instructions', models.TextField(help_text='List instructions separated by newlines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
